### PR TITLE
Delete SDK from AppTaskQueue

### PR DESCRIPTION
**Pull request by Honcharov12**
This:

- adds datastore client in tq to interact with datastore without SDK;
- deletes SDK from tq;
- adds venv for tq;
- moves creation of pull queue tables to AppDB.

### CODE REVIEW

**Comment by Honcharov12** [comment]
@cdonati earlier schema code was placed in appscale.taskqueue but it was called only once in appscale.datastore, the way to use still the same. So separate script can make it cleaner from one side and more implicit from another. It should be changed, but it is a different more specific task.

**Comment by Honcharov12** [comment]
http://ocd.appscale.net:8080/job/Daily%20Build/6333/

**Comment by jeanleonov** [comment]
@Honcharov12 thanks for the update around datastore client errors.
Though you'd still need to improve datastore error handling, in particular:
 - Datastore error name (extracted from code) and error details should be added to error raised by DatastoreClient. Then this information might be attached to TaskqueueResponse.
 - Datastore client should distinguish to groups of datastore errros (retry-able and permanent).

**Comment by Honcharov12** [comment]
**TQ stats**

Creates `appscale-taskqueue` virtual environment in `/opt/appscale_venvs/` directory. DatastoreClient allows to interact with Datastore without SDK.

Comparison on TaskQueue load tests with same parameters: 

- master branch - http://ocd.appscale.net:8080/view/all/job/TaskQueue-Load-Test/98/
  this branch - http://ocd.appscale.net:8080/view/all/job/TaskQueue-Load-Test/99/

- master branch - http://ocd.appscale.net:8080/view/all/job/TaskQueue-Load-Test/96/
  this branch - http://ocd.appscale.net:8080/view/all/job/TaskQueue-Load-Test/97/

- master branch - http://ocd.appscale.net:8080/view/all/job/TaskQueue-Load-Test/87/
  this branch - http://ocd.appscale.net:8080/view/all/job/TaskQueue-Load-Test/85/

Stats by e2e tests (5 on Cassandra implementation, 5 on Postgres):
- Add on master 0.262 s per 30 calls
  Add on this 0.488 s per 30 calls
- BulkAdd on master 0.213 s per 10 calls
  BulkAdd on this 0.625 s per 10 calls
- Delete on master 1.01 s per 20 calls
  Delete on this 2.68 s per 20 calls
- ModifyTaskLease on master 0.273 s per 50 calls
  ModifyTaskLease on this 0.560 s per 50 calls
- PurgeQueue on master 0.591 s per 120 calls
  PurgeQueue on this 1.01 s per 120 calls
- QueryAndOwnTasks on master 0.800 s per 40 calls
  QueryAndOwnTasks on this 1,89 s per 40 calls

Stats by hawkeye tests (10 runs):
- BulkAdd on master 4.46 s per 105 calls
  BulkAdd on this 4.06 s per 106 calls
- Delete on master 0.000858 s per 7 calls
  Delete on this 0.000595 s per 8 calls
- FetchQueueStats on master 0.0829 s per 3 calls
  FetchQueueStats on this 0.0452 s per 3 calls
- ModifyTaskLease on master 0.0577 s per 7 calls
  ModifyTaskLease on this 0.0847 s per 8 calls
- PurgeQueue on master 0.228 s per 15 calls
  PurgeQueue on this 0.209 s per 15 calls
- QueryAndOwnTasks on master 0.465 s per 24 calls
  QueryAndOwnTasks on this 0.58 s per 24 calls

**Comment by Honcharov12** [comment]
# Demo

Testing on 10000 adds to tq and 10000 leases gave such results (average):

On master
Adds user time: 50.23, system time: 10.04.
Leases user time: 77.02, system time: 15.02.

On this
Adds user time: 43.02, system time: 9.4.
Leases user time: 74.11, system time: 14.7.

There is very small performance improvement but the main goal is deleting SDK for making it more flexible and doing migration to py3 easier.

**Comment by Honcharov12** [comment]
http://ocd.appscale.net:8080/job/Daily%20Build/6495/

**Pull request merged**
