### PR TITLE
Untar app with AppController's permissions

### PR DESCRIPTION
**Pull request by cdonati**

### CODE REVIEW

**Comment by obino** [comment]
been confirmed on the user installation :+1:

**Comment by cdonati** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/857/

**Comment by obino** [comment]
@cdonati the run looks pretty good, a part from one test at https://ocd.appscale.com:8080/job/Hawkeye/3111/console. What's your take there? It seems odd that only one failed. Do you think it's the cluster that failed?

**Comment by cdonati** [comment]
I'm not sure if it's the cluster, but I did another run and didn't see that error: https://ocd.appscale.com:8080/job/Daily%20Build/863/

**Pull request merged**
