### PR TITLE
Remove incorrect zone parsing attempt from AppController

### PR DESCRIPTION
**Pull request by menivaitsi**
AppController is currently parsing the zone as JSON String.
This is an incorrect operation.

### CODE REVIEW

**Comment by obino** [comment]
haha nice find.

**Comment by menivaitsi** [comment]
Build: https://ocd.appscale.com:8080/job/Daily%20Build/2165/

**Comment by menivaitsi** [comment]
Build: https://ocd.appscale.com:8080/job/Daily%20Build/2182/

**Comment by menivaitsi** [comment]
There's a dependency on another branch that is not out yet. Closing this for now.

**Pull request closed without merging**
