### PR TITLE
Remove cool-down for up-scaling

### PR DESCRIPTION
**Pull request by obino**
Since we switched to capacity planning, we don't need to cool down
before re-evaluating the needed number of appservers, since we take into
account the pending ones.

### CODE REVIEW

**Comment by obino** [comment]
OCD run https://ocd.appscale.com:8080/job/Daily%20Build/3479/

**Comment by tmarballi** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/3494/

**Comment by obino** [comment]
OCD build https://ocd.appscale.com:8080/job/Daily%20Build/3719/

**Comment by cdonati** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/3756/

**Pull request merged**
