### PR TITLE
Use default JMX port

### PR DESCRIPTION
**Pull request by cdonati**
This also reduces some diffs in the Cassandra configuration files.

### CODE REVIEW

**Comment by cdonati** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/1531/

**Comment by menivaitsi** [comment]
👍

**Comment by cdonati** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/1537/

**Comment by cdonati** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/1599/

**Comment by menivaitsi** [comment]
@cdonati You might want to merge with master for the tests to pass.

**Comment by cdonati** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/1600/

**Pull request merged**
