### PR TITLE
Accept zone as String on server side

### PR DESCRIPTION
**Pull request by menivaitsi**
Current error:

> I, [2016-12-05T22:28:36.637441 #2953]  INFO -- : ==== Starting AppController (pid: 2953) ====
> [...]
> I, [2016-12-05T22:28:38.477478 #2953]  INFO -- : Converting 'autoscale' with value 'True'.
> **I, [2016-12-05T22:28:38.477506 #2953]  INFO -- : Converting 'zone' with value 'appscal1'.**
> I, [2016-12-05T22:28:38.477624 #2953]  INFO -- : Converting 'max_memory' with value '400'.
> I, [2016-12-05T22:28:38.477715 #2953]  INFO -- : Converting 'keyname' with value 'appscaledb195419f2894787a71d00cc3fc7bc4c'.
> I, [2016-12-05T22:28:38.477787 #2953]  INFO -- : Converting 'login' with value '192.168.100.70'.
> I, [2016-12-05T22:28:38.477831 #2953]  INFO -- : Converting 'appengine' with value '1'.
> **I, [2016-12-05T22:28:38.479813 #2953]  INFO -- : Fail to parse 'zone': ignoring it.**
> [...]

### CODE REVIEW

**Comment by menivaitsi** [comment]
Build: https://ocd.appscale.com:8080/job/Create-Eucalyptus-Image/3211/

**Comment by obino** [comment]
Tested on GCE and no warnng anylonger.

**Comment by menivaitsi** [comment]
Build: https://ocd.appscale.com:8080/job/Daily%20Build/2345/

**Comment by menivaitsi** [comment]
We don't pass the zone in the build template so here's the output from my test:

> I, [2016-12-06T01:02:29.668150 #3030]  INFO -- : Converting 'autoscale' with value 'True'.
**> I, [2016-12-06T01:02:29.668185 #3030]  INFO -- : Converting 'zone' with value 'appscal1'.**
> I, [2016-12-06T01:02:29.668303 #3030]  INFO -- : Converting 'max_memory' with value '400'.
> I, [2016-12-06T01:02:29.668396 #3030]  INFO -- : Converting 'keyname' with value 'appscale4cc40e53bed9470a9a1f143e9b63f386'.
> I, [2016-12-06T01:02:29.668461 #3030]  INFO -- : Converting 'login' with value '192.168.103.161'.
> I, [2016-12-06T01:02:29.668501 #3030]  INFO -- : Converting 'appengine' with value '1'.
> D, [2016-12-06T01:02:29.671734 #3030] DEBUG -- : Running mkdir -p /opt/appscale/apps
> D, [2016-12-06T01:02:29.673842 #3030] DEBUG -- : Output of mkdir -p /opt/appscale/apps was: 
> D, [2016-12-06T01:02:29.673946 #3030] DEBUG -- : set_parameters: set @options to {"max_images"=>"1", "infrastructure"=>"euca", "verbose"=>"True", "group"=>"appscale4cc40e53bed9470a9a1f143e9b63f386", "table"=>"cassandra", "user_commands"=>"[]", "autoscale"=>"True", "zone"=>"appscal1", "use_spot_instances"=>"False", "region"=>"appscal", "min_images"=>"1", "flower_password"=>"appscale", "max_memory"=>"400", "machine"=>"********", "instance_type"=>"m3.xlarge", "clear_datastore"=>"False", "keyname"=>"appscale4cc40e53bed9470a9a1f143e9b63f386", "EC2_URL"=>"********", "EC2_ACCESS_KEY"=>"********", "login"=>"********", "EC2_SECRET_KEY"=>"********", "appengine"=>"1", "controller_logs_to_dashboard"=>"False", "replication"=>"1", "ec2_access_key"=>"********", "ec2_secret_key"=>"********", "ec2_url"=>"********"}.

**Pull request merged**
