### PR TITLE
Don't write to ZK unchanged state

### PR DESCRIPTION
**Pull request by obino**

### CODE REVIEW

**Comment by obino** [comment]
OCD https://ocd.appscale.com:8080/job/Daily%20Build/2464/

**Comment by obino** [comment]
OCD run https://ocd.appscale.com:8080/job/Daily%20Build/2504/

**Comment by menivaitsi** [comment]
Build and demo?

**Comment by obino** [comment]
OCD run https://ocd.appscale.com:8080/job/Daily%20Build/2592

**Pull request merged**
