### PR TITLE
Install libffi-dev for the cryptography package

### PR DESCRIPTION
**Pull request by cdonati**

### CODE REVIEW

**Comment by cdonati** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/1562/

**Comment by cdonati** [comment]
This PR fixes the build on Precise.

**Comment by menivaitsi** [comment]
@cdonati Can you post the build #?

**Comment by cdonati** [comment]
In progress:
Precise: https://ocd.appscale.com:8080/job/Daily%20Build/1565/
Trusty: https://ocd.appscale.com:8080/job/Daily%20Build/1566/

**Pull request merged**
