### PR TITLE
Updated guestbook with wait handler

### PR DESCRIPTION
**Pull request by obino**

### CODE REVIEW

**Comment by obino** [comment]
OCD build https://ocd.appscale.com:8080/job/Daily%20Build/3893/

**Comment by dmitrii** [comment]
Yes, but what's in that /wp-content/uploads/2017/09/guestbook.tar.gz? :-)

**Comment by cdonati** [comment]
@dmitrii That's a good point, actually. I don't think blindly executing something that was fetched from a url is the best idea from a security standpoint.

**Comment by obino** [comment]
@cdonati @dmitrii we don't pull it in for our marketplace images, but only if the script is run manually. I would prefer to not having it in our repository,  or should we?

**Comment by cdonati** [comment]
Since it's a manual step, we could make it a optional argument that specifies a directory on the filesystem. I also don't think it should go in the repo.

**Comment by jeanleonov** [comment]
@obino , could you clarify if this PR is still topical?

**Comment by obino** [comment]
OCD https://ocd.appscale.com:8080/job/Daily%20Build/3933/

**Comment by obino** [comment]
OCD build https://ocd.appscale.com:8080/job/Daily%20Build/3938/

**Comment by obino** [comment]
OCD build https://ocd.appscale.com:8080/job/Daily%20Build/3972/

**Pull request merged**
