### PR TITLE
Add explicit dependency on sudo

### PR DESCRIPTION
**Pull request by obino**
Avoid issues like http://ocd.appscale.net:8080/job/Create-Docker-Container/5809/console

### CODE REVIEW

**Comment by obino** [comment]
OCD build http://ocd.appscale.net:8080/job/Daily%20Build/6521/

**Comment by sjones4** [comment]
Why do we need `sudo`? seems better to not use it.

**Comment by scragraham** [comment]
I believe @sjones4 is correct, we shouldn't need sudo.

**Comment by obino** [comment]
At this time sudo is used in few places, as part of the management that we talked about just this morning. I agree it would be nice to not needing it, but I'm not sure there is a way out of it easily. For not this PR makes it explicit so docker isn't failing out right.

**Comment by obino** [comment]
you are right, I think we can simply remove sudo from the install script. I will close this PR and create another one. Thanks @sjones4

**Pull request closed without merging**
