### PR TITLE
Don't include https port if it's not defined

### PR DESCRIPTION
**Pull request by cdonati**

### CODE REVIEW

**Comment by cdonati** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/1343/

**Comment by menivaitsi** [comment]
👍

**Comment by cdonati** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/1350/

**Comment by cdonati** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/1355/

**Pull request merged**
