### PR TITLE
Only the headnode should update dashboard data.

### PR DESCRIPTION
**Pull request by obino**

### CODE REVIEW

**Comment by obino** [comment]
OCD run https://ocd.appscale.com:8080/job/Daily%20Build/1366/

**Comment by menivaitsi** [comment]
Demo done. Build pending.

**Comment by obino** [comment]
OCD build https://ocd.appscale.com:8080/job/Daily%20Build/1379/

**Comment by obino** [comment]
OCD run https://ocd.appscale.com:8080/job/Daily%20Build/1381/

**Comment by obino** [comment]
OCD run https://ocd.appscale.com:8080/job/Daily%20Build/1384/

**Pull request merged**
