### PR TITLE
Use connection timeout instead of overriding default socket timeout

### PR DESCRIPTION
**Pull request by cdonati**
This brings urlfetch_stub.py up to date with the 1.8.0 SDK.

This pull request has the following additional side effects:
* ~~Adds SSL certificate verification by default to urlfetch~~
* Increases the max response size from 16 to 32 MB
* Fixes [an SDK](https://code.google.com/p/googleappengine/issues/detail?id=783) issue where debugging logging wouldn't correctly print URLFetch payloads
* Handles errors when trying to import fancy_urllib
* Fixes [an issue](https://code.google.com/p/googleappengine/issues/detail?id=3875) where the Content-length header was being incorrectly stored as an integer
* URLFetch will now return an error when the length of the URL requested exceeds 2048 characters
* Raises ApplicationError if fetching from a blacklisted port or if there is a socket timeout
* Fixes [an issue](https://code.google.com/p/googleappengine/issues/detail?id=2000) with the dev_appserver where HTTP HEAD always returned content-length: 0
* The URLFetch API now [supports multiple cookie headers](https://code.google.com/p/googleappengine/issues/detail?id=3379)
* URLFetch errors are more descriptive
* The URL Fetch service now [supports PATCH method requests](https://code.google.com/p/googleappengine/issues/detail?id=6316)
* Custom fetch functions passed to URLFetchService are now used instead of _RetrieveURL

### CODE REVIEW

**Comment by cdonati** [comment]
Precise: https://ocd.appscale.com:8080/job/Daily%20Build/968/
Trusty: https://ocd.appscale.com:8080/job/Daily%20Build/969/

**Comment by menivaitsi** [comment]
:+1:

**Comment by cdonati** [comment]
Precise: https://ocd.appscale.com:8080/job/Daily%20Build/1004/
Trusty: https://ocd.appscale.com:8080/job/Daily%20Build/1005/

**Comment by cdonati** [comment]
Precise: https://ocd.appscale.com:8080/job/Daily%20Build/1007/
Trusty: https://ocd.appscale.com:8080/job/Daily%20Build/1008/

**Pull request merged**
