### PR TITLE
enable md5_hash for blobstore

### PR DESCRIPTION
**Pull request by camtaylor**

### CODE REVIEW

**Comment by obino** [comment]
OCD run https://ocd.appscale.com:8080/job/Daily%20Build/236/

**Comment by obino** [comment]
Re-running OCD tests: https://ocd.appscale.com:8080/job/Daily%20Build/241/

**Comment by menivaitsi** [comment]
:+1:

**Comment by obino** [comment]
Previous OCD ran out of resources :( Re-run at https://ocd.appscale.com:8080/job/Daily%20Build/243/

**Comment by obino** [comment]
Had to do another run https://ocd.appscale.com:8080/job/Daily%20Build/245.

**Comment by camtaylor** [comment]
Hooray!

**Pull request merged**
