### PR TITLE
Install FoundationDB client libraries

### PR DESCRIPTION
**Pull request by jeanleonov**
- Download foundationdb-clients_6.1.8-1_amd64.deb from S3 and install it.
 - Add foundationdb package as a requirement for datastore.

### CODE REVIEW

**Comment by jeanleonov** [comment]
http://ocd.appscale.net:8080/job/Daily%20Build/6573/

**Comment by jeanleonov** [comment]
http://ocd.appscale.net:8080/job/Daily%20Build/6576/

**Comment by jeanleonov** [comment]
http://ocd.appscale.net:8080/job/Daily%20Build/6585/

**Comment by sjones4** [comment]
Why install the 6.1.11 python library and the 6.1.8 client package? would it be better to use the same version of each?

**Comment by jeanleonov** [comment]
I used latest version of both. Good point though. 

We should use specific version of deb package as it is manually downloaded, so 6.1.8 is our choice, but for python package I would just skip minor version and set 6.1.

Would it work?

**Comment by sjones4** [comment]
I think we need >= 6.1.8 since we use api version 610. Having looked into it a bit more 6.1.11 seems fine to me.

**Comment by jeanleonov** [comment]
http://ocd.appscale.net:8080/job/Daily%20Build/6602/

**Comment by jeanleonov** [comment]
@sjones4 using foundationdb~=6.1.8 should allow us using any version inside 6.1 greater than 6.1.8.
So we'll get some latest minor updates and bug fixes but won't get API changes.

**Pull request merged**
