### PR TITLE
Modify the monit stop script for taskqueue to account for ports.

### PR DESCRIPTION
**Pull request by tmarballi**

### CODE REVIEW

**Comment by obino** [comment]
Please add an OCD run.

**Comment by tmarballi** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/2752/

**Comment by tmarballi** [comment]
Sorry, forgot to pull in master, new build: https://ocd.appscale.com:8080/job/Daily%20Build/2753/

**Comment by tmarballi** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/2756/

**Pull request merged**
