### PR TITLE
Update the cursor format

### PR DESCRIPTION
**Pull request by cdonati**
Use the format introduced in the 1.5.1 SDK.

### CODE REVIEW

**Comment by menivaitsi** [comment]
:+1:

**Comment by cdonati** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/1231/

**Comment by cdonati** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/1252/

**Comment by cdonati** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/1257/

**Pull request merged**
