### PR TITLE
Simplify datastore error handling

### PR DESCRIPTION
**Pull request by cdonati**
If an error code is defined, the response body does not need to be specified. This prevents encoding issues in cases when a response message has required fields.

### CODE REVIEW

**Comment by cdonati** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/4281/

**Comment by cdonati** [comment]
Previously, it was common convention at this layer to do something like:
```
response = datastore_pb.Transaction()
response.set_app(project_id)
try:
  response.set_handle(datastore.create_txid())
  return response, 0, ''
except Exception:
  return response, error_code, 'error message'
```
and the parent function always tries to set the message with `response.Encode()`, which in the above example would raise `ProtocolBufferEncodeError: Required field: handle not set.` if there was an error creating a transaction ID.

The result is that the client would receive a 500 with a stacktrace as the body instead of a properly-formatted protobuf response with an error code set.

**Comment by jeanleonov** [comment]
Got it, thanks for the explanation.

**Comment by cdonati** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/4837/

**Pull request merged**
