### PR TITLE
Capture Net::ReadTimeout when using Net::HTTP

### PR DESCRIPTION
**Pull request by obino**
When using Net::HTTP to make a call to a service, we can back a
different exception for network timeout like:

/usr/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
        from /usr/lib/ruby/2.3.0/net/protocol.rb:136:in `readuntil'
        from /usr/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
        from /usr/lib/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
        from /usr/lib/ruby/2.3.0/net/http/response.rb:29:in `read_new'
        from /usr/lib/ruby/2.3.0/net/http.rb:1437:in `block in transport_request'
        from /usr/lib/ruby/2.3.0/net/http.rb:1434:in `catch'
        from /usr/lib/ruby/2.3.0/net/http.rb:1434:in `transport_request'
        from /usr/lib/ruby/2.3.0/net/http.rb:1407:in `request'
        from /root/appscale/AppController/lib/hermes_client.rb:23:in `block in make_call'
        from /usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
        from /usr/lib/ruby/2.3.0/net/http.rb:584:in `start'
        from /root/appscale/AppController/lib/hermes_client.rb:21:in `make_call'
        from /root/appscale/AppController/lib/hermes_client.rb:61:in `get_proxies_stats'
        from /root/appscale/AppController/lib/hermes_client.rb:79:in `get_proxy_stats'
        from /root/appscale/AppController/lib/hermes_client.rb:96:in `get_proxy_load_stats'
        from /root/appscale/AppController/djinn.rb:5935:in `block in get_application_load_stats'
        from /root/appscale/AppController/djinn.rb:5932:in `each'
        from /root/appscale/AppController/djinn.rb:5932:in `get_application_load_stats'
        from /root/appscale/AppController/djinn.rb:5190:in `get_scaling_info_for_version'
        from /root/appscale/AppController/djinn.rb:4928:in `block in scale_appservers'
        from /root/appscale/AppController/djinn.rb:4922:in `each'
        from /root/appscale/AppController/djinn.rb:4922:in `scale_appservers'
        from /root/appscale/AppController/djinn.rb:4951:in `scale_deployment'
        from /root/appscale/AppController/djinn.rb:1845:in `block in job_start'
        from /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /root/appscale/AppController/djinn.rb:1833:in `job_start'
        from /root/appscale/AppController/djinnServer.rb:162:in `<main>'

this PR catched the exception.

### CODE REVIEW

**Comment by obino** [comment]
OCD build https://ocd.appscale.com:8080/job/Daily%20Build/4498/

**Comment by obino** [comment]
OCD run for trusty: https://ocd.appscale.com:8080/job/Daily%20Build/4517/

**Comment by obino** [comment]
This PR is on hold: we have seen erratic behaviors that we need to investigate more.

**Comment by obino** [comment]
OCD build https://ocd.appscale.com:8080/job/Daily%20Build/4613/ Trusty build to come next

**Comment by obino** [comment]
OCD build https://ocd.appscale.com:8080/job/Daily%20Build/4633/

**Comment by scragraham** [comment]
going to merge without a demo since this issue was seen and resolved in customer environments.

**Pull request merged**
