### PR TITLE
Disable TLS v1 and enable TLSv1.1,TLSv1.2 for java7

### PR DESCRIPTION
**Pull request by ochre**

### CODE REVIEW

**Comment by cdonati** [comment]
Thanks for the pull request, @ochre. Would you mind giving me a brief description of what changes the included StreamHandlerFactory has compared to the one included in the SDK?

**Comment by ochre** [comment]
I removed the StreamHandlerFactory setting ` URL.setURLStreamHandlerFactory(factory)` in the install() method, this will allow using default Java Factory which supports properly the `-Dhttps.protocols=TLSv1.2`.

**Comment by cdonati** [comment]
https://ocd.appscale.com:8080/job/Daily%20Build/2836/

**Comment by sjones4** [comment]
This issue has been addressed via #2809 which uses a smaller fix made possible by more recent versions of Java 7.

**Pull request closed without merging**
