### PR TITLE
Use HelperFunctions.scp to copy app tarball

### PR DESCRIPTION
**Pull request by obino**
This PR modifies the scp helper funtion to be able to copy files from a
remote host, in order to use it to copy the tarball application.

### CODE REVIEW

**Comment by obino** [comment]
OCD run https://ocd.appscale.com:8080/job/Daily%20Build/2651/

**Comment by obino** [comment]
Re-run of the tools-test: https://ocd.appscale.com:8080/job/Tools-test/1397/

**Comment by obino** [comment]
OCD run https://ocd.appscale.com:8080/job/Daily%20Build/2664/

**Comment by obino** [comment]
Previous run got out of capacity issues: OCD run https://ocd.appscale.com:8080/job/Daily%20Build/2665/

**Comment by menivaitsi** [comment]
Please run a build after your final commit.

**Comment by obino** [comment]
OCD run https://ocd.appscale.com:8080/job/Daily%20Build/2681/

**Pull request merged**
